spring:
  # ?? ??? ?? ??
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/moim
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379
jwt:
  expiration: 30 # 30?
  secretKey: mySecret
