# 예외 처리를 커스텀하게 진행하기 위해 Whitelabel Error Page 옵션 OFF
server:
  error:
    whitelabel:
      enabled: false
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/moim
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379
jwt:
  expiration: 30 # 30분
  secretKey: mySecret
cloud:
  aws:
    credentials:
        access-key: AKIAQN5KP3UDEVXTVDNW
        secret-key: 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
    s3:
      bucket: moim-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
